version: "3.8"

services:
  database:
    container_name: libre_database
    image: postgresql:lastest
    environment:
      POSTGRES_USER: libre
      POSTGRES_PASSWORD: libre
      POSTGRES_DB: libre
    ports:
      - "5432:5432"
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
  rest-api:
    container_name: libre_rest_api
    image: ajalanbrown/libre-api:latest
    # build the Dockerfile, alternatively use an image.
    depends_on:
      - "postgres"