version: "3.8"

services:
  pgdb:
    container_name: libre_database
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=libre
      - POSTGRES_PASSWORD=libre
      - POSTGRES_DB=libre
    ports:
      - "5432:5000"
    volumes: 
      - ./packages/database/pgdata:/var/lib/postgresql/data
  rest-api:
    container_name: libre_rest_api
    image: ajalanbrown/libre-api:latest
    # build the Dockerfile, alternatively use an image.
    depends_on:
      - "pgdb"
    ports:
      - "8181:8181"