version: "3.8"

services:
  api:
    container_name: libre_rest_api
    build:
      context: ./
      dockerfile: docker/Dockerfile.HotReload
    ports:
      - "8080:8080"
      - "5432:5432"
    environment:
      - PORT=8080
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  db:
    image: postgres:12-alpine
    container_name: libre_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=libre
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api

networks:
  web_api:
    driver: bridge