version: "3.8"

services:
  web:
    image: ajalanbrown/libre-api:latest
    container_name: libre_rest_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    # volumes:
    #   - ./:/app
    tty: true 
    networks:
      - web_api

  postgesql:
      image: postgres:12-alpine
      container_name: libre_postgesql
      ports:
        - "9090:9090"
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=libre
      # volumes:
      #    - ./pgdata:/var/lib/postgresql/data
      networks:
        - web_api       
networks:
    web_api:
      driver: bridge