#default os but development can be in any os
FROM ubuntu:22.04 

#add admin user and dir
RUN apt-get -y update
RUN useradd -m admin && apt-get install -y fish && apt-get install -y golang-go && apt-get install -y ca-certificates
#create api dir
RUN cd home && cd admin && mkdir api && cd api 
# #bundle app source
COPY . ./home/admin/api

#ru specific api dir
WORKDIR /home/admin/api

RUN go get
RUN su - admin
CMD ["echo","complete"]

EXPOSE 8080
RUN go run main.go

