server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: postgresql
  PostgresqlPort: 5432
  PostgresqlUser: libre
  PostgresqlPassword: libre
  PostgresqlDbname: libre
  PostgresqlSslmode: false
  PgDriver: pgx


session:
  Name: session-id
  Prefix: api-session
  Expire: 3600



mongodb:
  MongoURI: uristring


