server:
  AppVersion: 1.0.0
  Port: :8080
  CookieName: jwt-token
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: "fa673e30fb7afcfcd4965e2e4365673dc86b19ba6158b09200f392f0aac4f015"
  PostgresqlPort: 5432
  PostgresqlUser: "libre"
  PostgresqlPassword: "libre"
  PostgresqlDbname: "libre"
  PostgresqlSslmode: false
  PgDriver: postgres

session:
  Name: user-session
  Expire: 3600
