server:
  AppVersion: 1.0.0
  Port: :8080
  CookieName: jwt-token
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: "localhost"
  PostgresqlPort: 5000
  PostgresqlUser: "libre"
  PostgresqlPassword: "libre"
  PostgresqlDbname: "libre"
  PostgresqlSslmode: false
  PgDriver: postgres

session:
  Name: user-session
  Expire: 3600
