server:
  AppVersion: 1.0.0
  Port: :8181
  CookieName: jwt-token
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: "locahost"
  PostgresqlPort: 5432
  PostgresqlUser: "postgres"
  PostgresqlPassword: "postgres"
  PostgresqlDbname: "libre"
  PostgresqlSslmode: false
  PgDriver: pgx

session:
  Name: user-session
  Expire: 3600
