server:
  AppVersion: 1.0.0
  Port: :8080
  PprofPort: :8282
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: "localhost"
  PostgresqlPort: 5432
  PostgresqlUser: "libre"
  PostgresqlPassword: "libre"
  PostgresqlDbname: "libre"
  PostgresqlSslmode: false
  PgDriver: pgx

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

mongodb:
  MongoURI: uristring
